
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND AS COMA COUNT DESIGUAL DISTINCT FROM GROUP_BY HAVING ID IGUAL IN INNER_JOIN LEFT_JOIN MAX MAYOR_IZQ MAY_IGUAL_IZQ MENOR_IZQ MEN_IGUAL_IZQ MIN NUMERO ON OR ORDER_BY PAREN_DER PAREN_IZQ PUNTO PUNTOCOMA SELECT WHEREquery : SELECT columnas FROM tablas\n             | SELECT columnas FROM tablas WHERE condicioncolumnas : columna\n                   | columna COMA columnacolumna : ID PUNTO ID\n               | ID PUNTO ID AS IDtablas : tabla\n              | tabla COMA tablatabla : ID AS ID\n             | ID IDcondicion : columnas IGUAL columnas'
    
_lr_action_items = {'SELECT':([0,],[2,]),'$end':([1,4,9,10,12,13,16,20,21,22,23,25,],[0,-3,-1,-7,-4,-5,-10,-2,-8,-9,-6,-11,]),'ID':([2,6,7,8,11,14,15,17,18,24,],[5,11,5,13,16,5,11,22,23,5,]),'FROM':([3,4,12,13,23,],[6,-3,-4,-5,-6,]),'IGUAL':([4,12,13,19,23,],[-3,-4,-5,24,-6,]),'COMA':([4,10,13,16,22,23,],[7,15,-5,-10,-9,-6,]),'PUNTO':([5,],[8,]),'WHERE':([9,10,16,21,22,],[14,-7,-10,-8,-9,]),'AS':([11,13,],[17,18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'query':([0,],[1,]),'columnas':([2,14,24,],[3,19,25,]),'columna':([2,7,14,24,],[4,12,4,4,]),'tablas':([6,],[9,]),'tabla':([6,15,],[10,21,]),'condicion':([14,],[20,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> query","S'",1,None,None,None),
  ('query -> SELECT columnas FROM tablas','query',4,'p_query','grupo02_m.py',97),
  ('query -> SELECT columnas FROM tablas WHERE condicion','query',6,'p_query','grupo02_m.py',98),
  ('columnas -> columna','columnas',1,'p_columnas','grupo02_m.py',102),
  ('columnas -> columna COMA columna','columnas',3,'p_columnas','grupo02_m.py',103),
  ('columna -> ID PUNTO ID','columna',3,'p_columna_con_tabla_antepuesta','grupo02_m.py',107),
  ('columna -> ID PUNTO ID AS ID','columna',5,'p_columna_con_tabla_antepuesta','grupo02_m.py',108),
  ('tablas -> tabla','tablas',1,'p_tablas','grupo02_m.py',134),
  ('tablas -> tabla COMA tabla','tablas',3,'p_tablas','grupo02_m.py',135),
  ('tabla -> ID AS ID','tabla',3,'p_tabla_con_alias','grupo02_m.py',139),
  ('tabla -> ID ID','tabla',2,'p_tabla_con_alias','grupo02_m.py',140),
  ('condicion -> columnas IGUAL columnas','condicion',3,'p_condicion','grupo02_m.py',161),
]
